[package]
name = "greet-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
compromise = { version = "0.1.0", path = "../compromise" }
libloading = "0.8.3"
notify = "6.1.1"
